#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
Apply ModelFin_106 linear-cycle common-mode potential gauge correction to a raw
soft-label-only evaluation directory.

This script expects ModelFin_106/gauge_config.json generated by
build_ModelFin106_from_ModelFin105_linearCycleGauge.py.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple

import numpy as np


def _jfloat(x: Any) -> Optional[float]:
    try:
        v = float(x)
    except Exception:
        return None
    if not math.isfinite(v):
        return None
    return v


def _load_json(path: Path) -> Dict[str, Any]:
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text('', encoding='utf-8')
        return
    keys: List[str] = []
    for row in rows:
        for k in row.keys():
            if k not in keys:
                keys.append(k)
    with path.open('w', newline='', encoding='utf-8-sig') as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def _find_eval_npz(eval_dir: Path, explicit: Optional[str] = None) -> Path:
    if explicit:
        p = Path(explicit)
        if not p.is_absolute():
            p = eval_dir / p
        if not p.exists():
            raise FileNotFoundError(f'Explicit eval npz not found: {p}')
        return p.resolve()
    preferred = [
        'eval_sampled_arrays_cycles5_100_v2_massclosed_softlabel_only.npz',
        'eval_sampled_arrays_cycles5_100_softlabel_only.npz',
    ]
    for name in preferred:
        p = eval_dir / name
        if p.exists():
            return p.resolve()
    candidates = sorted(eval_dir.glob('eval_sampled_arrays*.npz'))
    if not candidates:
        raise FileNotFoundError(f'No eval_sampled_arrays*.npz found in {eval_dir}')
    return candidates[0].resolve()


def _metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, Any]:
    yt = np.asarray(y_true, dtype=np.float64).reshape(-1)
    yp = np.asarray(y_pred, dtype=np.float64).reshape(-1)
    mask = np.isfinite(yt) & np.isfinite(yp)
    yt = yt[mask]
    yp = yp[mask]
    n = int(yt.size)
    if n == 0:
        return {'n': 0, 'mae': None, 'rmse': None, 'maxabs': None, 'bias_mean': None, 'corr': None, 'r2': None, 'nmae': None, 'std_ratio_pred_over_label': None}
    err = yp - yt
    mae = float(np.mean(np.abs(err)))
    rmse = float(np.sqrt(np.mean(err * err)))
    maxabs = float(np.max(np.abs(err)))
    bias = float(np.mean(err))
    yt_std = float(np.std(yt))
    yp_std = float(np.std(yp))
    corr = float('nan')
    if n > 1 and yt_std > 0 and yp_std > 0:
        corr = float(np.corrcoef(yt, yp)[0, 1])
    denom = float(np.sum((yt - np.mean(yt)) ** 2))
    r2 = float('nan') if denom <= 0 else float(1.0 - np.sum(err * err) / denom)
    yrange = float(np.max(yt) - np.min(yt))
    nmae = float('nan') if yrange <= 0 else float(mae / yrange)
    std_ratio = float('nan') if yt_std <= 0 else float(yp_std / yt_std)
    return {
        'n': n,
        'mae': _jfloat(mae),
        'rmse': _jfloat(rmse),
        'maxabs': _jfloat(maxabs),
        'bias_mean': _jfloat(bias),
        'corr': _jfloat(corr),
        'r2': _jfloat(r2),
        'nmae': _jfloat(nmae),
        'label_min': _jfloat(np.min(yt)),
        'label_max': _jfloat(np.max(yt)),
        'label_range': _jfloat(yrange),
        'label_std': _jfloat(yt_std),
        'pred_min': _jfloat(np.min(yp)),
        'pred_max': _jfloat(np.max(yp)),
        'pred_std': _jfloat(yp_std),
        'std_ratio_pred_over_label': _jfloat(std_ratio),
    }


def _repeat_cycle_ids(cycle_id_time: np.ndarray, flat_len: int, nr: int) -> np.ndarray:
    cid = np.asarray(cycle_id_time).reshape(-1)
    if cid.size == flat_len:
        return cid
    if cid.size * int(nr) == int(flat_len):
        return np.repeat(cid, int(nr))
    raise ValueError(f'Cannot align cycle ids: len={cid.size}, nr={nr}, flat_len={flat_len}')


def _variable_arrays(arr: Mapping[str, np.ndarray]) -> Dict[str, Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    out: Dict[str, Tuple[np.ndarray, np.ndarray, np.ndarray]] = {}
    cid_p = np.asarray(arr['cycle_id_potential']).reshape(-1).astype(int)
    out['phis_c'] = (np.asarray(arr['phis_c_true']).reshape(-1), np.asarray(arr['phis_c_pred']).reshape(-1), cid_p)
    out['phie'] = (np.asarray(arr['phie_true']).reshape(-1), np.asarray(arr['phie_pred']).reshape(-1), cid_p)

    cid_cs = np.asarray(arr['cycle_id_cs']).reshape(-1).astype(int)
    nr_a = int(np.asarray(arr['r_a']).reshape(-1).size)
    nr_c = int(np.asarray(arr['r_c']).reshape(-1).size)
    for var, nr in [('cs_a', nr_a), ('theta_a', nr_a), ('cs_c', nr_c), ('theta_c', nr_c)]:
        true_key = f'{var}_true'
        pred_key = f'{var}_pred'
        if true_key not in arr or pred_key not in arr:
            continue
        yt = np.asarray(arr[true_key]).reshape(-1)
        yp = np.asarray(arr[pred_key]).reshape(-1)
        if yt.size == 0 or yp.size == 0:
            continue
        cid = _repeat_cycle_ids(cid_cs, yt.size, nr)
        out[var] = (yt, yp, cid)
    return out


def _global_and_cycle_metrics(arr: Mapping[str, np.ndarray], cycle_from: int, cycle_to: int) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    glob: Dict[str, Any] = {}
    rows: List[Dict[str, Any]] = []
    for var, (yt, yp, cid) in _variable_arrays(arr).items():
        m_all = (cid >= int(cycle_from)) & (cid <= int(cycle_to))
        glob[var] = _metrics(yt[m_all], yp[m_all])
        for c in range(int(cycle_from), int(cycle_to) + 1):
            m = m_all & (cid == c)
            if not np.any(m):
                continue
            row = {'variable': var, 'cycle_id': int(c)}
            row.update(_metrics(yt[m], yp[m]))
            rows.append(row)
    return glob, rows


def _common_mode_diag(arr_before: Mapping[str, np.ndarray], arr_after: Mapping[str, np.ndarray], cycle_from: int, cycle_to: int) -> Dict[str, Any]:
    cid = np.asarray(arr_before['cycle_id_potential']).reshape(-1).astype(int)
    m = (cid >= int(cycle_from)) & (cid <= int(cycle_to))
    def cm(arr: Mapping[str, np.ndarray]) -> np.ndarray:
        phie_err = np.asarray(arr['phie_pred'], dtype=np.float64).reshape(-1) - np.asarray(arr['phie_true'], dtype=np.float64).reshape(-1)
        phis_err = np.asarray(arr['phis_c_pred'], dtype=np.float64).reshape(-1) - np.asarray(arr['phis_c_true'], dtype=np.float64).reshape(-1)
        return 0.5 * (phie_err + phis_err)
    def diff(arr: Mapping[str, np.ndarray]) -> np.ndarray:
        phie_err = np.asarray(arr['phie_pred'], dtype=np.float64).reshape(-1) - np.asarray(arr['phie_true'], dtype=np.float64).reshape(-1)
        phis_err = np.asarray(arr['phis_c_pred'], dtype=np.float64).reshape(-1) - np.asarray(arr['phis_c_true'], dtype=np.float64).reshape(-1)
        return phis_err - phie_err
    def s(x: np.ndarray) -> Dict[str, Any]:
        x = np.asarray(x, dtype=np.float64).reshape(-1)
        x = x[np.isfinite(x)]
        return {'n': int(x.size), 'mae': _jfloat(np.mean(np.abs(x))) if x.size else None, 'rmse': _jfloat(np.sqrt(np.mean(x*x))) if x.size else None, 'bias_mean': _jfloat(np.mean(x)) if x.size else None, 'std': _jfloat(np.std(x)) if x.size else None}
    return {
        'cycle_from': int(cycle_from),
        'cycle_to': int(cycle_to),
        'common_mode_error_before': s(cm(arr_before)[m]),
        'common_mode_error_after': s(cm(arr_after)[m]),
        'differential_phis_minus_phie_error_before': s(diff(arr_before)[m]),
        'differential_phis_minus_phie_error_after': s(diff(arr_after)[m]),
        'interpretation': 'A successful common-mode gauge correction should reduce common-mode error while leaving the differential phis_c-phie error and concentration branches unchanged.',
    }


def _try_plots(output_dir: Path, rows_after: List[Dict[str, Any]]) -> None:
    try:
        import matplotlib.pyplot as plt
    except Exception:
        return
    pdir = output_dir / 'plots_linear_gauge_corrected'
    pdir.mkdir(parents=True, exist_ok=True)
    for var in ['phis_c', 'phie', 'theta_c', 'cs_c', 'theta_a', 'cs_a']:
        rows = [r for r in rows_after if r.get('variable') == var]
        if not rows:
            continue
        x = np.asarray([r['cycle_id'] for r in rows], dtype=float)
        y = np.asarray([r['mae'] for r in rows], dtype=float)
        plt.figure(figsize=(10, 4.5))
        plt.plot(x, y, marker='.', linewidth=0.8)
        plt.xlabel('cycle_id')
        plt.ylabel(f'{var} MAE after ModelFin_106 gauge')
        plt.tight_layout()
        plt.savefig(pdir / f'per_cycle_mae_{var}_ModelFin106_linearGauge.png', dpi=180)
        plt.close()


def main() -> int:
    ap = argparse.ArgumentParser(description='Apply ModelFin_106 linear-cycle common-mode gauge correction to raw evaluation arrays.')
    ap.add_argument('--eval_dir', type=Path, default=Path('EvalFin_106_cycles5_100_v2_massclosed_candidate_linearGauge_raw_softlabel_only'))
    ap.add_argument('--eval_npz', type=str, default=None)
    ap.add_argument('--model_dir', type=Path, default=Path('ModelFin_106'))
    ap.add_argument('--gauge_config', type=Path, default=None)
    ap.add_argument('--output_dir', type=Path, default=Path('EvalFin_106_cycles5_100_v2_massclosed_candidate_linearCycleGauge_softlabel_only'))
    ap.add_argument('--cycle_from', type=int, default=5)
    ap.add_argument('--cycle_to', type=int, default=100)
    ap.add_argument('--save_npz', action='store_true', default=True)
    ap.add_argument('--no_plots', action='store_true')
    args = ap.parse_args()

    eval_dir = args.eval_dir.resolve()
    model_dir = args.model_dir.resolve()
    output_dir = args.output_dir.resolve()
    cfg_path = args.gauge_config.resolve() if args.gauge_config else (model_dir / 'gauge_config.json').resolve()
    if not cfg_path.exists():
        raise FileNotFoundError(f'gauge_config.json not found: {cfg_path}. Run build_ModelFin106_from_ModelFin105_linearCycleGauge.py first.')
    gauge = _load_json(cfg_path)
    slope = float(gauge['linear_bias_slope_V_per_cycle'])
    intercept = float(gauge['linear_bias_intercept_V'])

    eval_npz = _find_eval_npz(eval_dir, args.eval_npz)
    with np.load(eval_npz, allow_pickle=False) as data:
        arr_before = {k: data[k] for k in data.files}

    required = ['cycle_id_potential', 'phie_pred', 'phis_c_pred', 'phie_true', 'phis_c_true']
    missing = [k for k in required if k not in arr_before]
    if missing:
        raise KeyError(f'Missing keys in eval npz: {missing}. Available: {sorted(arr_before)}')

    cid_p = np.asarray(arr_before['cycle_id_potential']).reshape(-1).astype(float)
    offset = -(slope * cid_p + intercept)
    arr_after = dict(arr_before)
    arr_after['phie_pred'] = np.asarray(arr_before['phie_pred'], dtype=np.float64).reshape(-1) + offset
    arr_after['phis_c_pred'] = np.asarray(arr_before['phis_c_pred'], dtype=np.float64).reshape(-1) + offset

    metrics_before, rows_before = _global_and_cycle_metrics(arr_before, args.cycle_from, args.cycle_to)
    metrics_after, rows_after = _global_and_cycle_metrics(arr_after, args.cycle_from, args.cycle_to)
    diag = _common_mode_diag(arr_before, arr_after, args.cycle_from, args.cycle_to)

    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / 'gauge_application_summary.json', {
        'model': 'ModelFin_106_linearCycleCommonModeGauge',
        'eval_npz': str(eval_npz),
        'gauge_config': str(cfg_path),
        'cycle_from': int(args.cycle_from),
        'cycle_to': int(args.cycle_to),
        'linear_bias_slope_V_per_cycle': _jfloat(slope),
        'linear_bias_intercept_V': _jfloat(intercept),
        'offset_formula': 'offset_to_add_V = -(slope * cycle_id + intercept)',
        'offset_stats_over_potential_samples': {
            'n': int(offset.size),
            'mean': _jfloat(np.mean(offset)),
            'min': _jfloat(np.min(offset)),
            'max': _jfloat(np.max(offset)),
            'std': _jfloat(np.std(offset)),
        },
        'note': 'Only phie_pred and phis_c_pred are shifted by the same common-mode offset. Concentration/theta arrays are unchanged.',
    })
    _write_json(output_dir / 'metrics_global_before_raw.json', metrics_before)
    _write_json(output_dir / 'metrics_global_corrected.json', metrics_after)
    _write_json(output_dir / 'potential_common_mode_diagnostic_before_after.json', diag)
    _write_csv(output_dir / 'metrics_by_cycle_before_raw.csv', rows_before)
    _write_csv(output_dir / 'metrics_by_cycle_corrected.csv', rows_after)

    if args.save_npz:
        to_save = {k: v for k, v in arr_before.items()}
        to_save['phie_pred_before_linear_gauge'] = np.asarray(arr_before['phie_pred'])
        to_save['phis_c_pred_before_linear_gauge'] = np.asarray(arr_before['phis_c_pred'])
        to_save['phie_pred'] = np.asarray(arr_after['phie_pred'], dtype=np.float32)
        to_save['phis_c_pred'] = np.asarray(arr_after['phis_c_pred'], dtype=np.float32)
        to_save['potential_common_mode_offset_to_add'] = np.asarray(offset, dtype=np.float32)
        np.savez_compressed(output_dir / 'eval_sampled_arrays_ModelFin106_linearGauge_corrected.npz', **to_save)

    if not args.no_plots:
        _try_plots(output_dir, rows_after)

    def _fmt(v: Any) -> str:
        if v is None:
            return 'None'
        try:
            fv = float(v)
        except Exception:
            return str(v)
        if not math.isfinite(fv):
            return 'nan'
        return f'{fv:.6g}'

    print('[OK] ModelFin_106 linear-cycle gauge applied')
    print(f'  output_dir: {output_dir}')
    for key in ['phis_c', 'phie', 'theta_c', 'cs_c', 'theta_a', 'cs_a']:
        if key in metrics_after:
            m = metrics_after[key]
            print(f"{key:8s} MAE={_fmt(m.get('mae'))} RMSE={_fmt(m.get('rmse'))} R2={_fmt(m.get('r2'))} corr={_fmt(m.get('corr'))} NMAE={_fmt(m.get('nmae'))}")
    print('  common_mode_mae_before:', diag['common_mode_error_before']['mae'])
    print('  common_mode_mae_after: ', diag['common_mode_error_after']['mae'])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
