from __future__ import annotations
import argparse, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT_DIR = Path(__file__).resolve().parent
for p in [ROOT, SCRIPT_DIR]:
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from d15_p4c_utils import load_json, write_json


def parse_args():
    p = argparse.ArgumentParser(description='D15-P4C collect final scorecard.')
    p.add_argument('--config', default='configs/d15_p4c_batch56_remaining14_replay_config.json')
    p.add_argument('--preflight-json', required=True)
    p.add_argument('--build-json', required=True)
    p.add_argument('--audit-json', required=True)
    p.add_argument('--resource-json', required=True)
    p.add_argument('--out-json', required=True)
    return p.parse_args()


def main() -> int:
    args = parse_args(); cfg = load_json(args.config)
    pre = load_json(args.preflight_json)
    build = load_json(args.build_json)
    audit = load_json(args.audit_json)
    resource = load_json(args.resource_json)
    target = int(cfg['thresholds']['expected_target_count'])
    statuses = {
        'preflight_status': pre.get('overall_status'),
        'build_status': build.get('overall_status'),
        'audit_status': audit.get('overall_status'),
        'resource_smoke_status': resource.get('overall_status'),
    }
    failures = []
    if int(pre.get('found_raw_count', 0)) < target:
        failures.append('not_all_target_raw_mat_files_found')
    if int(build.get('pass_count', 0)) < target or int(build.get('error_count', 999)) > 0:
        failures.append('not_all_target_replay_profiles_built')
    if int(audit.get('pass_count', 0)) < target or int(audit.get('fail_count', 999)) > 0:
        failures.append('not_all_target_replay_profiles_passed_audit')
    final = 'PASS' if not failures else 'REVIEW'
    score = {
        'stage': 'D15-P4C Batch-5/6 remaining14 replay-profile completion + resource smoke',
        'final_status': final,
        **statuses,
        'target_cell_count': target,
        'raw_found_count': int(pre.get('found_raw_count', 0)),
        'replay_built_pass_count': int(build.get('pass_count', 0)),
        'replay_build_error_count': int(build.get('error_count', 0)),
        'replay_audit_pass_count': int(audit.get('pass_count', 0)),
        'replay_audit_fail_count': int(audit.get('fail_count', 0)),
        'resource_smoke_cuda_available': resource.get('torch_cuda_smoke', {}).get('cuda_available'),
        'failures': failures,
        'allowed_claim_if_pass': 'Replay profiles are ready for the remaining 14 Batch-5/6 cells; D15-P4D may generate their P2Dlite-RG soft labels.',
        'not_allowed_claims': [
            'Do not claim the remaining 14 soft labels have been generated by D15-P4C.',
            'Do not claim GPU is used by the NumPy P2Dlite-RG generator unless P4D backend is rewritten.',
            'Do not claim experimental internal-state truth for future cs_a/cs_c labels.'
        ]
    }
    write_json(score, args.out_json)
    print('[D15-P4C scorecard] final_status:', final)
    return 0 if final == 'PASS' else 1

if __name__ == '__main__':
    raise SystemExit(main())
