#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gv1.pipeline.manifest import load_manifest, merge_cli_overrides, write_resolved_manifest
from gv1.pipeline.npz_utils import list_npz_keys


def main() -> None:
    ap = argparse.ArgumentParser(description='GV1 training entry. This version validates inputs and creates a training run scaffold.')
    ap.add_argument('--manifest', default=None)
    ap.add_argument('--prepared_dir', default=None, help='Directory generated by gv1_generate_softlabels.py')
    ap.add_argument('--solution_npz', default=None)
    ap.add_argument('--output_dir', required=True)
    ap.add_argument('--mode', default='dry_run_scaffold', choices=['dry_run_scaffold'])
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)
    manifest = merge_cli_overrides(manifest, prepared_dir=args.prepared_dir, solution_npz=args.solution_npz, output_dir=args.output_dir, mode=args.mode)
    out_dir = Path(manifest['output_dir'])
    out_dir.mkdir(parents=True, exist_ok=True)

    solution_npz = manifest.get('solution_npz')
    if not solution_npz and manifest.get('prepared_dir'):
        cand = Path(manifest['prepared_dir']) / 'solution_replay_profile.npz'
        if cand.exists():
            solution_npz = str(cand)
    if not solution_npz:
        raise ValueError('solution_npz or prepared_dir is required')
    keys = list_npz_keys(solution_npz)
    required = {'t_global_s', 'I_profile', 'voltage_exp'}
    missing = sorted(required - set(keys))
    if missing:
        raise ValueError(f'solution npz missing required keys: {missing}')

    train_plan = {
        'stage': 'GV1 training scaffold',
        'status': 'validated_not_trained',
        'reason': 'PINN network/loss modules are intentionally not attached in this entry package yet.',
        'solution_npz': solution_npz,
        'solution_keys': keys,
        'next_expected_modules': [
            'gv1/model.py',
            'gv1/output_transform.py',
            'gv1/losses.py',
            'gv1/trainer.py',
        ],
    }
    (out_dir / 'training_plan.json').write_text(json.dumps(train_plan, ensure_ascii=False, indent=2), encoding='utf-8')
    write_resolved_manifest(manifest, out_dir / 'resolved_train_manifest.json')
    print(json.dumps({'ok': True, 'output_dir': str(out_dir), 'status': 'validated_not_trained', 'solution_npz': solution_npz}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
