# D16-P5A example commands for QJW-2 / PINN-for-ASSB-V1
# Run from project root:
#   C:\Users\Tiga_QJW\Desktop\ASSB_Scheme_V1\PINN-for-ASSB-V1

$SoftLabelRoot = "E:\XJTU battery dataset\_gv1_cache\xjtu_softlabels_p2dlite_rg_v1_D15_ALL55_FINAL"
$CacheRoot = "E:\XJTU battery dataset\_gv1_cache"

# 1) Preflight only
python scripts\gv1_d16_p5a_transfer_eval.py `
  --soft-label-root $SoftLabelRoot `
  --output-root "$CacheRoot\xjtu_d16_p5a_existing_transfer_preflight" `
  --preflight-only

# 2) Evaluate existing predictions already generated by a D15 model
# Change $PredictionRoot to the directory that contains prediction.npz files.
$PredictionRoot = "$CacheRoot\xjtu_d16_p5a_predictions_D15P2"
python scripts\gv1_d16_p5a_transfer_eval.py `
  --model-name "D15_P2_8cell_existing_model" `
  --soft-label-root $SoftLabelRoot `
  --prediction-root $PredictionRoot `
  --output-root "$CacheRoot\xjtu_d16_p5a_eval_D15P2_on_ALL55" `
  --seen-cells "configs\d16_p5a_seen_cells_template.txt" `
  --projection-modes "raw,projected"

# 3) Generate predictions by calling an existing inference script, then evaluate
# Replace scripts\YOUR_EXISTING_D15_INFER_SCRIPT.py and $ModelDir with actual paths.
# Keep dry-run first to verify generated commands.
$ModelDir = "$CacheRoot\xjtu_d15_p2_existing_model_dir"
python scripts\gv1_d16_p5a_transfer_eval.py `
  --model-name "D15_P2_8cell_existing_model" `
  --soft-label-root $SoftLabelRoot `
  --prediction-root $PredictionRoot `
  --output-root "$CacheRoot\xjtu_d16_p5a_eval_D15P2_dryrun" `
  --model-dir $ModelDir `
  --run-inference `
  --dry-run `
  --seen-cells "configs\d16_p5a_seen_cells_template.txt" `
  --inference-command-template "python scripts\YOUR_EXISTING_D15_INFER_SCRIPT.py --model-dir {model_dir} --soft-label-npz `"{soft_label_npz}`" --output-npz `"{output_npz}`" --device cuda:0"
